version: '2'

services:
   db:
     container_name: "MySQL"
     image: "mysql:5.7"
     volumes:
       - data-volume:/var/lib/db
     ports:
       - "3306:3306"
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD: "root"
       MYSQL_DATABASE: obzyvalki
       MYSQL_USER: "testUser"
       MYSQL_PASSWORD: "1234"

   web:
     container_name: "whoIsYana"
     depends_on:
       - db
     image: whoisyana/v1:latest
     ports:
       - "8081:8081"
     restart: unless-stopped
     environment:
       WEB_DB_HOST: db:3306
       WEB_DB_PASSWORD: "1234"
       MYSQL_USER: "testUser"

volumes:
   data-volume:

