version: '2'

services:
   db:
     image: "mysql:5.7"
     ports:
       - "3306:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: "root"
       MYSQL_DATABASE: obzyvalki
       MYSQL_USER: "testUser"
       MYSQL_PASSWORD: "1234"

   web:
     links:
       - db
     depends_on:
       - db
     image: whoisyana/v1:latest
     ports:
       - "8081:8081"
     restart: unless-stopped
     environment:
       WEB_DB_HOST: "172.18.0.1:3306"
       WEB_DB_PASSWORD: "1234"


#version: '2'
#
#services:
#  wordpress:
#    image: wordpress:latest
#    links:
#      - database:mariadb
#    environment:
#      - WORDPRESS_DB_USER=wordpress
#      - WORDPRESS_DB_NAME=mydbname
#      - WORDPRESS_TABLE_PREFIX=ab_
#      - WORDPRESS_DB_PASSWORD=password
#      - WORDPRESS_DB_HOST=mariadb
#      - MYSQL_PORT_3306_TCP=3306
#    restart: unless-stopped
#    ports:
#      - "test.dev:80:80"
#    working_dir: /var/www/html
#    volumes:
#     - ./wordpress/:/var/www/html/
#  database:
#   image: mariadb:latest
#   environment:
#     - MYSQL_ROOT_PASSWORD=password
#     - MYSQL_DATABASE=mydbname
#     - MYSQL_USER=wordpress
#     - MYSQL_PASSWORD=password
#   restart: unless-stopped
#   ports:
#     - "3306:3306"